#!/usr/bin/env python3
"""Unit tests for AI attribution detection, including Grok and xAI coverage."""

import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from ai_ethics_enforcer import AIEthicsEnforcer  # noqa: E402


class GrokAttributionTests(unittest.TestCase):
    def setUp(self):
        self.enforcer = AIEthicsEnforcer()

    def test_rejects_grok_co_author(self):
        message = (
            "Add feature\n\n"
            "Co-authored-by: Grok <noreply@x.ai>"
        )
        violations = self.enforcer.check_commit_message(message)
        self.assertTrue(violations)

    def test_rejects_xai_co_author(self):
        message = (
            "Add feature\n\n"
            "Co-authored-by: xAI <noreply@x.ai>"
        )
        violations = self.enforcer.check_commit_message(message)
        self.assertTrue(violations)

    def test_rejects_generated_by_grok(self):
        message = "Add feature\n\nGenerated by Grok"
        violations = self.enforcer.check_commit_message(message)
        self.assertTrue(violations)

    def test_rejects_grok_commit_phrasing(self):
        message = "Grok generated the parser tests"
        violations = self.enforcer.check_commit_message(message)
        self.assertTrue(violations)

    def test_accepts_human_co_author(self):
        message = (
            "Add feature\n\n"
            "Co-authored-by: Victor J. Quinones <victor@futuretranz.com>"
        )
        violations = self.enforcer.check_commit_message(message)
        self.assertEqual(violations, [])

    def test_still_rejects_copilot_co_author(self):
        message = (
            "Add feature\n\n"
            "Co-authored-by: GitHub Copilot <copilot@github.com>"
        )
        violations = self.enforcer.check_commit_message(message)
        self.assertTrue(violations)

    def test_grok_starter_file_is_compliant(self):
        repo_root = os.path.join(os.path.dirname(__file__), '..')
        grok_starter = os.path.join(repo_root, 'GROK.md')
        result = self.enforcer.enforce_policy(grok_starter, 'file')
        self.assertTrue(result['compliant'], result['violations'])


if __name__ == '__main__':
    unittest.main()
